### ISSUE TITLE
Can markdown-oxide be added to the Mason registry?

### ISSUE THREAD

**Issue by knpwrs** [Feel-ix-343/markdown-oxide#1]
This would make it easy to configure alongside other LSPs directly inside neovim: https://github.com/mason-org/mason-registry

**Comment by Feel-ix-343** [comment]
So I opened two PRs for this. One here https://github.com/mason-org/mason-registry/pull/4683 and one here https://github.com/neovim/nvim-lspconfig/pull/3030

Note that even once these are merged, you will still need to configure nvim cmp yourself. I am looking into options to make this automatic (let me know if you have any ideas!)

**Comment by knpwrs** [comment]
I stopped maintaining my own configuration and switched to https://github.com/LazyVim/LazyVim, so my best idea would be a lazyvim extra that can be configured as such:

```lua
{ import = "lazyvim.plugins.extras.lang.markdown_oxide" }
```

Then that would handle installation and LSP setup. This could either be contributed to LazyVim or distributed as a standalone package.

**Comment by Feel-ix-343** [comment]
Great idea!

**Comment by Feel-ix-343** [comment]
Update: So it seems that the mason registry is not very active in PR reviews. I am sad about this because I think this is the best way to install LSs for neovim on all platforms.

For now, the package is listed on the AUR as `markdown-oxide-git` (`paru{/yay} -S markdown-oxide-git` and if you are not on arch, you can always compile from source.

I am working on getting this into other package managers now as well

**Comment by Feel-ix-343** [comment]
done!

(development is too active for a binary release, but this should work for now)

https://github.com/mason-org/mason-registry/pull/4683

**Comment by knpwrs** [comment]
Awesome, thank you!
