### ISSUE TITLE
Support LSP Incoming and Outgoing

### ISSUE THREAD

**Issue by ray-x** [Feel-ix-343/markdown-oxide#14]
The vscode markdown lsp uses customer message `markdown/getReferencesToFileInWorkspace`.
How do I get something similar in `oxide`?

**Comment by Feel-ix-343** [comment]
In the [readme](https://github.com/Feel-ix-343/markdown-oxide?tab=readme-ov-file#features) I documented the lsp_references functionality! (if it was not descriptive enough, give me some tell me!)

To get references to a file, put your cursor in the first character of the first line of a file, and call `lua vim.lsp.buf.references()`. Map this to a keymapping for easier use. 

This behavior with the Quickfix list is okay, but I **STRONGLY** recommend using a plugin like [telescope](https://github.com/nvim-telescope/telescope.nvim) or [lspsaga](https://github.com/nvimdev/lspsaga.nvim) to show the references; the UX is infinitely better. 

If you are using Telescope, like I am, call `Telescope lsp_references` to show the references. I set up keymappings for this [in my config](https://github.com/Feel-ix-343/Neovim-Config/blob/main/lua/plugin/LspSetup.lua). 

Here is a quick video to better show it


[lspreferences.zip](https://github.com/Feel-ix-343/markdown-oxide/files/14469901/lspreferences.zip)


And to show the reference count on the end of the line, set up codelens by following the directions [here](https://github.com/Feel-ix-343/markdown-oxide?tab=readme-ov-file#neovim)

**Comment by Feel-ix-343** [comment]
Close when you are ready

**Comment by Feel-ix-343** [comment]
Oh wait; Are you talking about a neovim command/a lua API function?

**Comment by ray-x** [comment]
I do not think reference and doc backlink are the same.
You can show references/backlinks to a file if your cursor is on [[filename]] in filename-b.md
But the backlink works in a way that you already opened `filename.md` and need to find all references to [[filename]]. A similar feature in `obsidian.nvim` is 

> :ObsidianBacklinks for getting a picker list of references to the current buffer.

Alternatively, the lsp server can use incomingCall message to achieve that.

**Comment by Feel-ix-343** [comment]
You are right that they are different! I will implement incoming :heavy_check_mark: 

As for the position: it does *work* because all forms of references/referenceables (tags, headings, links, ...) are more than one character; so the user can also move to [1, 2] to get references to them -- while [1, 1] will *always* be for the file. 

But is this ideal? I am not so sure; I am okay with it but I am very open to other ideas. I can think of: 
- [1, 1]
- Anywhere in the file that doesn't have another referenceable/reference. 
- .. what you do think?

**Comment by ray-x** [comment]
In fact, there is a corner case when `[[` is concealed

<img width="110" alt="image" src="https://github.com/Feel-ix-343/markdown-oxide/assets/1681295/8c510909-bac6-4556-8f0e-8f4a927e1ad5">


I prefer

> Anywhere in the file that doesn't have another referenceable/reference.

As it does not require jumping to the very beginning of file to check back-links.

**Comment by Feel-ix-343** [comment]
... it also is easier in guis like zed and vscode as you can click anywhere with the mouse

**Comment by Feel-ix-343** [comment]
In ea7742a I changed where your cursor should be for files.

**Comment by Feel-ix-343** [comment]
Hey this' been open for a while; I am doing a major refactor right now which will cover it. Just wanted to let you know. 

I am also realizing that incoming and outgoing links are give a much more powerful UI experience for backlinking because the LS can attach descriptions (which in moxide's case are backlink previews) to the view. Very excited; big things incoming!

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
