### ISSUE TITLE
Creating a new link also adds the name of the folder

### ISSUE THREAD

**Issue by sohanglal** [Feel-ix-343/markdown-oxide#18]
I am a veteran Obsidian user and have the option `New link format` set to `Shortest path when possible` in it.

When I use `moxide`, on inserting a link that is in a subfolder, moxide also adds the folder name to the link. 
Is there a way to turn this off?

**Comment by Feel-ix-343** [comment]
There are no config options yet, but in response to #2, the markdown link completions choose shortest path (only the filename actually).

I will surely add this as a config option in the future. 

There is also the question of which should be the default. In #2 the argument was that shortest path links would need to be modified less. I feel that the same argument could be applied to wiki links. However, my intuition is that wikilinks should be more self descriptive -- e.g filenames with spaces and then rendered specially when linking to headings. This implies that full path should be the default as it is more descriptive. 

Also note that the user should really not be affected by this option too much, as `moxide` does a good job at searching through paths (in fact, it does the filtering and ranking on the server because the lsp clients are too damn slow!); Anyway, Typing a filename will always give you the thing you are looking for.

**Comment by sohanglal** [comment]
> There are no config options yet, but in response to https://github.com/Feel-ix-343/markdown-oxide/issues/2, the markdown link completions choose shortest path (only the filename actually).

Thanks! Should I keep this open till the option isn't added?

> Also note that the user should really not be affected by this option too much, as moxide does a good job at searching through paths (in fact, it does the filtering and ranking on the server because the lsp clients are too damn slow!); Anyway, Typing a filename will always give you the thing you are looking for.

Fair enough

**Comment by Feel-ix-343** [comment]
Yea keeping it open is good; Ill reference it in a "config" issue

**Comment by Feel-ix-343** [comment]
In response to #26, I'm just going to changed the default completions to be just filenames in this commit b60fc9e. Update, and your issues should be solved!

**Comment by sohanglal** [comment]
Thanks a lot!

**Comment by Feel-ix-343** [comment]
Happy to help! I hope you are getting something out of this. 

Please let me know if there are other issues!
