### ISSUE TITLE
Question: Feature parity with Marksman

### ISSUE THREAD

**Issue by sQVe** [Feel-ix-343/markdown-oxide#2]
Hey,

I've been trying this LSP out, coming from Marksman, and it's working great in certain cases but not in others. I have followed the recommended setup, but I still cannot get go-to definitions / references to work. Some of the basic LSP features that Marksman provides are missing

Have I set something up incorrectly, or is this currently broken? The roadmap lists most of these things as supported, which makes me confused.

🍻

**Comment by Feel-ix-343** [comment]
Thank you for the comment!!

Ok so generally, this language server is compatible with obsidian style linking, which is wikilinks to the file name `[[file]]` . Marksman references (I think) are based on the first heading in the file so the links are `[[heading]]`. I believe this is configurable, but this is the default. That is one potential reason definitions and references are not working. To further diagnose, please tell me what linking syntax you are using.

**Comment by Feel-ix-343** [comment]
Also you bring up a good point about specifying the markdown syntax so that people coming from other pkms, editors, and language servers do not get confused. I have just added [this](https://github.com/Feel-ix-343/markdown-oxide?tab=readme-ov-file#note-on-linking-syntax) to the documentation. Do you have any other suggestions about syntax items to be more specific about?

**Comment by sQVe** [comment]
> That is one potential reason definitions and references are not working. To further diagnose, please tell me what linking syntax you are using.

Yes, this seems to be the issue. I'm typically using regular Markdown links rather than wiki-style links. 

> This is a major issue and I am going to work on this soon.

Glad to hear! 👏🏼 

---

I'm also noting that reference-style links aren't supported, while footnotes work fine.
```markdown
<!-- This is supported. -->
[^1]: Linux is an open-source operating system.

<!-- This is not supported. -->
[debian]: https://www.debian.org
```

**Comment by sQVe** [comment]
> Do you have any other suggestions about syntax items to be more specific about?

I think people coming from Marksman will get confused by not being able to get references for a file when running goto references on the main header of it. I think the way you've set it up makes sense, since this LSP provides greater completion for headers, but it will still confuse people.

**Comment by Feel-ix-343** [comment]
Ok so I believe I added support for Markdown (not wiki) style links in ac4feee . Try it out in let me know how it works

**Comment by Feel-ix-343** [comment]
> 
> [debian]: https://www.debian.org
> ```

OK so I am not familiar with this syntax. Could you explain it? Is that something referenceable?

**Comment by sQVe** [comment]
> Could you explain it? Is that something referenceable?

The name is link reference definition according to the CommonMark specification.

https://spec.commonmark.org/0.31.2/#link-reference-definitions

I commonly use it when I want to reference a URL multiple times within a document.

```markdown
This sentence links to a [example] website. This sentence links to the [same example][example] website.

[Example] is useful when writing examples.

[example]: https://example.com
```

**Comment by sQVe** [comment]
> Ok so I believe I added support for Markdown (not wiki) style links in [ac4feee](https://github.com/Feel-ix-343/markdown-oxide/commit/ac4feeee4eb53f6304a6091e14c4b9df1a9a700a) . Try it out in let me know how it works

Yes, it works 👍🏼. However, the change seems to have introduced an issue with resolving links. Both Marksman and Obsidian allow me to link to other notes that reside in different directories without needing to include the directory in the link.

Assuming I have `0-inbox/foo.md` and `3-resources/bar.md`, if I want to link to `foo.md` from within `bar.md`, I can simply use `[[foo.md]]` instead of `[[0-inbox/foo.md]]`.

![image](https://github.com/Feel-ix-343/markdown-oxide/assets/2284724/8d6f405d-62f5-4618-ac8e-db2304723e82)

**Comment by Feel-ix-343** [comment]
Ok so I added this to the markdown links in cc3509e (pushing when I get off of my school's wifi)

I will add for wiki links soon too

**Comment by sQVe** [comment]
@Feel-ix-343 Works great. It does not work for wikilinks though.

**Comment by Feel-ix-343** [comment]
Yep; working on that now

**Comment by Feel-ix-343** [comment]
Great! The wikilink support will be added soon. Also (for all viewing this,
not just @sQVe) obsidian does not allow spaces in the markdown link path.
To have spaces using normal MD syntax, you would have to replace the spaces
with %20 . There is an extended syntax (not obsidian specific, but obsidian
supported) where you put <> around the path ([display text](<path with/
spaces>) to allow for spaces.


To address this, Moxide does allow for the spaces even without the <>s for
those who may not be using obsidian and want the simplest linking option,
while also handling %20s and <>s for those who want to maintain obsidian
compatibility. (This is totally up for discussion too.)


And another question: I would like to implement completions markdown links,
but given all of the possibilities for paths in MD links, I do not know
which to choose for the default completion-generated syntax; What are your
thoughts?

**Comment by sQVe** [comment]
> obsidian does not allow spaces in the markdown link path

Spaces should never exist in a path, period. But that's just me. 😉

> I would like to implement completions markdown links, but given all of the possibilities for paths in MD links, I do not know which to choose for the default completion-generated syntax; What are your thoughts?

Mimicking how Obsidian does it is likely your best bet. I would probably decide the implementation based on the following factors:

- 100% compatibility with Obsidian, preferably mimicking how it handles this.
- Pick paths that are less likely to become broken if a note is moved.
  - `foo.md` is more resilient than `qux/foo.md`.
- Shorter paths are nicer than longer paths.

---

When it comes to deciding which link syntax to use, links or wikilinks, I believe it's very much a matter of personal preference—and should remain that way _(I personally prefer default links before wikilinks)_. 

However, I would appreciate it if `markdown-oxide` could support header completion within a linked document when using wikilinks.

```markdown
<!-- 20240228-foo.md -->

# Foo

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

Given the note above, I would be grateful if linking to the document could be as simple as using `[[20240228-foo]]` or `[[20240228-foo|Foo]]`.

**Comment by Feel-ix-343** [comment]
I assume that the header would be the content for fuzzy finding? And more specifically only the first header of the file? 

In your example: Type `[[foo` and get a completion (one of many) with text-edit `[[20240228-foo|Foo]]` for wiki links or type `[](Foo` and get text-edit `[Foo](20240228-foo)` as a completion.  

I could also do `[Foo` -> `[Foo](20240228-foo)` (though this would conflict with footnote completions, which I could also to requiring `[^` to complete)

Is this along the lines of what you are thinking? Tell me to elaborate if necessary.

**Comment by sQVe** [comment]
I would try to keep it as simple as possible. Completion should consistently give you either filenames or headers, but not both. When typing `[[`, filename completion should be provided. Once you have `[[20240228-foo` and type `|`, you should get completion for the first header of the file. The same principle would apply to regular links, but adapted to their syntax.

The primary reason I want this feature is to avoid having to type out all the headers unnecessarily.

---

> In your example: Type [[foo and get a completion (one of many) with text-edit [[20240228-foo|Foo]] for wiki links or type [](Foo and get text-edit [Foo](20240228-foo) as a completion.

For clarity: Typing `[[foo` should bring up completion options like `[[20240228-foo`. For `[](Foo)`, the completion should suggest `[](20240228-foo)`. After completing to `[[20240228-foo|` and `[|](20240228-foo)`, the cursor should be at the position to allow for text completion of the first header in the file.

**Comment by dawsers** [comment]
The hardest part of an LSP server is probably parsing. Regular expressions can become very long and complicated. There are very subtle bugs that can creep every now and then, making the code very hard to maintain. I had a look at the code, and it seems that is the place where most of the future hard work will be: capturing code blocks, complicated links, etc. I see [sQVe](https://github.com/sQVe) is helping you debug those.

The reason why I am making this comment is I had an idea I wanted to share here. you could use tree sitter for parsing. There is a quite mature implementation of the [markdown parser](https://github.com/tree-sitter-grammars/tree-sitter-markdown), and there are [Rust bindings for tree sitter](https://crates.io/crates/tree-sitter). It this was a C++ project I would definitely help you, but I am quite illiterate when it comes to Rust. I could help you with queries for grouping, semantic tokens etc, though. I have my own version of those for markdown. The advantage of this is you could decouple some of the nastiest bugs from your project, and if you found bugs, help them fix them if you have the time, but without the same level of commitment. This adds a dependency on others, but at the same time you get a lot of work already done "for free", and if any of their decisions don't suit you, you fork from an advanced state.

It is just an idea.

**Comment by Feel-ix-343** [comment]
Thank you for the comment!

So originally I started by using the markdown treesitter parser, but the issue was that with my vault of notes (4K files), treesitter was extremely slow. Parsing synchronously took around [2.3 seconds](https://github.com/Feel-ix-343/markdown-oxide/blob/8b34fdea275eaf906e32c0c9688c6238bb8812f1/SequentialPerformance.md) and while parsing async (on a 20 thread CPU) took [657ms](https://github.com/Feel-ix-343/markdown-oxide/blob/8b34fdea275eaf906e32c0c9688c6238bb8812f1/ParallelPerformance.md). Now on my vault regex parsing is near instant (less than 5ms I believe). The other thing is that the parser is not obsidian specific; it will get the general markdown stuff (links ...), but not the specifics like the obsidian query language, dataview, and the obsidian yaml -- which I want to eventually support (I'm very excited about giving query/dataview completions and calculating/rendering queries for `find_references` and hover!). 

However, I do definitely agree that regex is *not* ideal. There are several glaring issues:
- As the rust regex package does not support recursive parsing, it is impossible (to my knowledge?) to parse links that have links (that have links...) in them. For example, there are times when we use links in heading names `# heading [[link]]`; a link to this -- if in `file.md` -- would be `[[file#heading [[link]]]]`; Given that there could be infinite levels of nesting, I cannot guarantee that *all* links in links will be parsed; right now, the regex will not even parse `[[file#heading [[link]]]]`. For now, I will probably work around this by handling one or two levels of links in links.
- The regex to parse links (probably not ideal; but kinda intuitive) is this: `\[\[(?<filepath>[^\[\]\|\.\#]+)(\#(?<infileref>[^\[\]\.\|]+))?(\|(?<display>[^\[\]\.\|]+))?\]\]` (which is for the [rust regex](https://docs.rs/regex/latest/regex/) syntax). **This is unbearably ugly and offputting**!


Anyway, right now it *works* and it is fast (very important :100: ), but real parsing is certainly on the future path of this project. The options I am considering are
- Using treesitter in combination with regex to get feature-rich obsidian support (thank you @dawsers for mentioning this)
- Writing a recursive parser using some rust parsing library ([chumsky](https://github.com/zesterer/chumsky) and [nom](https://github.com/rust-bakery/nom) seem appealing). The perfect library would allow me to reuse some other person's markdown parsing code, extending it with obsidian features. 
- Making the regex better and/or using a recursive regex parser
- ... [any suggestions?]


Again, thank you for the comment; I am am quite excited that this project is gaining some momentum -- my confidence is boosted a bit from this. I say: ***Lets make the best markdown LS for PKM in existence***!

**Comment by dawsers** [comment]
Fair enough. I didn't know the history of your project.

However, the current parser isn't as full featured yet. The markdown tree sitter one has to do two passes to support code blocks etc., and *markdown-oxide* doesn't support those yet. I am sure you will be able to write something very fast, but it won't be as fast as it is now, in part because of the issues you mention, and in part because you will still need to add more passes to support all the features. On the other hand, 4000 notes in less than one second...where do I sign?! :-) That is just startup cost to build the hash structures for the vault, references afterwards update instantly, and added/modified files only need to update partially, I guess. For most people that is not an issue, any LSP server for programming languages takes a lot longer to index a project and provide semantic highlighting.

Thank you again for your dedication. I was just trying to think about how we could make your life easier, of course.

**Comment by Feel-ix-343** [comment]
> on for the first header of the file. The same principle would apply to regular links, but adap



> I would try to keep it as simple as possible. Completion should consistently give you either filenames or headers, but not both. When typing `[[`, filename completion should be provided. Once you have `[[20240228-foo` and type `|`, you should get completion for the first header of the file. The same principle would apply to regular links, but adapted to their syntax.
> 
> The primary reason I want this feature is to avoid having to type out all the headers unnecessarily.
> 
> > In your example: Type `[[foo` and get a completion (one of many) with text-edit `[[20240228-foo|Foo]]` for wiki links or type `[](Foo` and get text-edit `[Foo](20240228-foo)` as a completion.
> 
> For clarity: Typing `[[foo` should bring up completion options like `[[20240228-foo`. For `[](Foo)`, the completion should suggest `[](20240228-foo)`. After completing to `[[20240228-foo|` and `[|](20240228-foo)`, the cursor should be at the position to allow for text completion of the first header in the file.

Currently, the reason that file heading completions are sent with file completions is to allow searching through headings when making links. To me, this is a major feature missing from Obsidian; one only can search headings after typing the `#` in `[[file#`. That being said, it is only my preference, and given Obsidian's choice and what you are saying, clearly some people prefer to complete items this way. **I am happy to implement both options** and set up a config file to determine which to use. (Ill add some commands to nvim-lspconfig to toggle these boolean settings!). 

With all of this, though, there is the question of which behavior should be the default. To me, the arguments are:
1. (Mine) I want to grep through headings in files while prompting for link completions. For example, I have a file for this language server that tracks my tasks and ideas. I divide this file in to sections for completions, parsing, rename, ... that are all headings. Often, I will type `[[Completions` then select the `[[Markdown Oxide#Completions]]` completion to record a completion-related idea when writing in my daily note. (I then view all completion ideas by getting references to the `#Completions` heading in the `Markdown Oxide.md` file.) For this workflow, the completion headings is quite useful. 
2. (@sQVe) Only complete file names. I assume this is preferred to not be overwhelmed by completions and because one may rarely link to headings. This makes sense to me, but @sQVe let me know if I am missing something. The other argument for this is that this is the default Obsidian behavior, and people migrating from Obsidian would be most familiar with it. 


Given the point about default Obsidian behavior, I am now favoring 2. . However, I view 1. as being extremely useful. 

If we were to go with 2., I would want to make sure that behavior 1. is well advertised and easy to enable.

**Comment by Feel-ix-343** [comment]
> Fair enough. I didn't know the history of your project.
> 
> However, the current parser isn't as full featured yet. The markdown tree sitter one has to do two passes to support code blocks etc., and _markdown-oxide_ doesn't support those yet. I am sure you will be able to write something very fast, but it won't be as fast as it is now, in part because of the issues you mention, and in part because you will still need to add more passes to support all the features. On the other hand, 4000 notes in less than one second...where do I sign?! :-) That is just startup cost to build the hash structures for the vault, references afterwards update instantly, and added/modified files only need to update partially, I guess. For most people that is not an issue, any LSP server for programming languages takes a lot longer to index a project and provide semantic highlighting.
> 
> Thank you again for your dedication. I was just trying to think about how we could make your life easier, of course.

I am so happy to work on this project, so please have absolutely no hesitation to make suggestions!

Im going to open a discussion for this so we can talk more.

**Comment by sQVe** [comment]
> With all of this, though, there is the question of which behavior should be the default.

I think you should go with that you think makes the most sense. I'm happy as long as there is a config option to change it. I could very well be converted too.

**Comment by sQVe** [comment]
@Feel-ix-343 Do you have a possible ETA for when completion for links could be in place? It's basically the only thing left for me to move over fully.

**Comment by Feel-ix-343** [comment]
Ill do it today 🙂

**Comment by Feel-ix-343** [comment]
Note some support is here ed068bd004a9a89d6dc8b23f34f8a075e85492ef but I am working on the more advanced cases now

**Comment by Feel-ix-343** [comment]
Ok I added it and its quite cool! Here is a quick video showing completions off. It is in the `TestFiles` dir on this repo so you (all) should be able to test similarly if you want!


![markdownlinkcompletions](https://github.com/Feel-ix-343/markdown-oxide/assets/88951499/39ff863d-a759-4831-bbc0-6060084f7159)

**Comment by Feel-ix-343** [comment]
These updated features are from commit 139ce57cc4e7e404271ad3230372776415b5eee3 BTW

**Comment by sQVe** [comment]
@Feel-ix-343 It works quite well; however, there are issues with duplicate completions for files (refer to the attached image below). I receive one completion with just the filename and another including the directory path. The "advanced" header completion functions correctly with the completion item that contains the directory, but not with the one that lacks it.

![image](https://github.com/Feel-ix-343/markdown-oxide/assets/2284724/d8d4eb69-5c94-4445-8a2b-30d6dc4be91c)
_Note: There is no preview available, which is odd and likely indicative of a bug._

---

Another problem I encounter with the "advanced" completion is the insertion of fragmented text while navigating through the options.

![image](https://github.com/Feel-ix-343/markdown-oxide/assets/2284724/adf230da-0fc1-4d58-b997-16a9353b6f23)

**Comment by Feel-ix-343** [comment]
I think that the fragments are just a part of nvim-cmp snippets. Rust Language Server does it too at times. I believe you can undo the insert through `cmp.mapping.abort()` which should be bound to `<C-e>`. I will see if I can make these look better, however. 

![2024-03-02_20-18](https://github.com/Feel-ix-343/markdown-oxide/assets/88951499/52d53c22-79c3-4581-b5b4-80218c04721d)



1.  a4009b25ad2199ae2979475f1d03afebf051d93a Should fix the duplication. Note that in the state of that commit, you will not get filename completions and only get full path completions. 
2. Your second comment is related to duplication as well. In order to support both the short and full paths, I believe there would need to be duplicates in the completions. This is awkward, though we must pick one. 

This point is a good argument
> Pick paths that are less likely to become broken if a note is moved

So I've switched the default completions to the filename completions in the latest. 

I have set it up so that you can still fuzzy match the path, but can only complete the filename. Shown here: 

![path](https://github.com/Feel-ix-343/markdown-oxide/assets/88951499/0b157760-6960-40b9-8f3d-0e3b90a23dbe)

**Comment by Feel-ix-343** [comment]
@sQVe close this if ready!

**Comment by sQVe** [comment]
@Feel-ix-343 Closing since this issue has gone out of scope since forever 😆

**Comment by sQVe** [comment]
@Feel-ix-343 Also, completions for regular links works great now. Only thing missing, I guess, is heading completion for wikilinks. No rush from my end since I don't use them.
