### ISSUE TITLE
creating files consistent with obsidian structure

### ISSUE THREAD

**Issue by anandkumar89** [Feel-ix-343/markdown-oxide#56]
Obsidian allows users to specify where dailyNotes, templates etc are stored. 

currently configuration doesn't allow to replicate same structure. As it allows creating files, there should be some config to allow users to define file placement (esp. dailynotes)

I realise this doesn't fall under the purview of a lsp but I could think of alternate solution than to include a config in lsp.

**Comment by Feel-ix-343** [comment]
Ok this is a great idea!

There is configuration supported for the LS through `.config/moxide/settings.toml` or `.moxide.toml` in the workspace root (or as the workspace root!). See the readme for options. Here we could specify where these types of files would be placed. 

Daily notes should be pretty easy because the LS already detects this them.

We could start off there and see what else to specify. Once moxide supports templates, this setting could easily be added too.

**Comment by Feel-ix-343** [comment]
how does that work for you? We have
- Code action creates in the proper location
- LSP Commands Today, Yesterday, Tomorrow, Daily ... will create the daily notes file in the proper location
